### ISSUE TITLE
Update to VEC 2.0.1

### ISSUE THREAD

**Issue by beckerjohannes** [4Soft-de/vec-model#119]
## General Troubleshooting

- [X] I have checked for similar questions / issues.
- [X] I have updated to the [latest version](https://mvnrepository.com/artifact/com.foursoft.vecmodel).

## Feature Request

Yesterday VEC 2.0.1 (Bugfix Release) was published. The `v2x` Variant of the model should be upgrade to this schema version. Extend Mappings (`xjb`) should be the same as for VEC 2.0.1.

See: https://ecad-wiki.prostep.org/specifications/vec/v201/

**Comment by DManstrator** [comment]
Closed due to archiving, see the ReadMe.
